name: Publish packages
'on':
  push:
    branches:
      - master

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Setup pnpm
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      # Install dependencies
      - run: HUSKY=0 pnpm install --prod --frozen-lockfile

      # Bump version
      - run: tools/scripts/bump-version.sh

      # Reflect changes to dev branch
      - uses: 01Joseph-Hwang10/gh-actions@forward-merge-v2
        with:
          from: master
          to: dev

      # Publish packages
      - run: pnpm nx run-many -t publish
